export const jednosci = [
  "",
  " jeden",
  " dwa",
  " trzy",
  " cztery",
  " pięć",
  " sześć",
  " siedem",
  " osiem",
  " dziewięć",
];
export const nascie = [
  "",
  " jedenaście",
  " dwanaście",
  " trzynaście",
  " czternaście",
  " piętnaście",
  " szesnaście",
  " siedemnaście",
  " osiemnaście",
  " dziewiętnaście",
];
export const dziesiatki = [
  "",
  " dziesięć",
  " dwadzieścia",
  " trzydzieści",
  " czterdzieści",
  " pięćdziesiąt",
  " sześćdziesiąt",
  " siedemdziesiąt",
  " osiemdziesiąt",
  " dziewięćdziesiąt",
];
export const setki = [
  "",
  " sto",
  " dwieście",
  " trzysta",
  " czterysta",
  " pięćset",
  " sześćset",
  " siedemset",
  " osiemset",
  " dziewięćset",
];
export const grupy = [
  ["", "", ""],
  [" tysiąc", " tysiące", " tysięcy"],
  [" milion", " miliony", " milionów"],
  [" miliard", " miliardy", " miliardów"],
  [" bilion", " biliony", " bilionów"],
  [" biliard", " biliardy", " biliardów"],
  [" trylion", " tryliony", " trylionów"],
];
